version: "3.8"

services:
  mysql_db:
    image: percona:5.7.32
    container_name: popchef_mysql
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --log_bin_trust_function_creators=1 --max_allowed_packet=128M --default_storage_engine=InnoDB --character-set-client-handshake=FALSE --binlog_format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    cap_add:
      - SYS_NICE
    healthcheck:
      test: mysql --user=root --password=root --execute "show databases"
      interval: 5s
      timeout: 1s
      retries: 3
    ports:
      - "3306:3306"

  adminer:
    image: adminer:latest
    container_name: popchef-adminer
    restart: unless-stopped
    ports:
      - 8000:8080
    depends_on:
      - mysql_db
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db
